FROM ubuntu:latest

# Select your back-end client. Currently only aria2 is supported.
ARG CLIENT='aria2' # transmission-cli rtorrent deluge-console

RUN apt update && \
    apt install -y ${CLIENT} && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Add the root dir
COPY root/ /

# Replace this next line with a call to pierdat, one call per data source. For
# URI, currently only magnet links and torrent files are supported.

## RUN pierdat URI /path/to/destination

# Docker entrypoint runs pierdatd in the background 
# and then execs the CMD
ENTRYPOINT [ "/entrypoint.sh" ]

# Which in this example defaults to a shell
CMD [ "/bin/bash" ]